// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    //'NUUA202510 : 변경내용'
    //Cannot use @TaskAction annotation on method AbstractKotlinCompile.execute()
    //because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
    //
    // 1.6.0 이상 빌드 사용 필요.
    // 참고 자료: https://youtrack.jetbrains.com/issue/KT-47867
    // 이전 코드 : ext.kotlin_version = '1.5.20'
    ext.kotlin_version = '1.9.20'
//    ext.kotlin_version = '1.7.1'
    repositories {
        google()
        mavenCentral()

    }
    dependencies {
        //'NUUA202510 : 변경내용'
        // 16KB 및 Android 15 설정을 위한 AGP 버전 변경
        // AGP 버전 8.3~8.5에서는 앱이 기본적으로 16KB로 정렬됩니다.
        // 참고 자료: https://developer.android.com/guide/practices/page-sizes?hl=ko#build
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {
            url 'https://repository.map.naver.com/archive/maven'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
