apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'kto.smarttour'
//      서명 정보
    signingConfigs {
        release {
            storeFile file('../../keystore/Vienam.keystore')
            storePassword 'oniontech939'
            keyAlias 'mykey'
            keyPassword 'oniontech939'
        }
    }
    defaultConfig {
        applicationId "kto.smarttour"
        minSdkVersion 21
        //'NUUA202510 : 변경내용'
        // Android 16 SDK 설정
        compileSdk 36
        targetSdkVersion 36
        versionCode 117
        versionName "4.3.8"
        multiDexEnabled true
        buildConfigField("String", "SIGN_ACCESS_KEY", sign_access_key)
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFile getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFile 'proguard-commons.pro'
            proguardFile 'proguard-firebase.pro'
            proguardFile 'proguard-rules.pro'
            proguardFile 'proguard-stg.pro'
        }
        debug {
            minifyEnabled true
            shrinkResources false
            proguardFile getDefaultProguardFile('proguard-android-optimize.txt')
            proguardFile 'proguard-commons.pro'
            proguardFile 'proguard-firebase.pro'
            proguardFile 'proguard-rules.pro'
            proguardFile 'proguard-stg.pro'
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
        }
    }


    buildFeatures {
        dataBinding true
        //'NUUA202510 : 변경내용'
        // Build Type contains custom BuildConfig fields, but the feature is disabled
        // 참고 자료: https://android.googlesource.com/platform/tools/base/+/370c706fb6553dc5952e10323a81f2b195405c3f%5E%21/
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.md', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.md', 'META-INF/NOTICE.txt', 'META-INF/INDEX.LIST', 'META-INF/notice.txt', 'META-INF/ASL2.0']
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.5.0'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'

    implementation 'com.google.android.material:material:1.2.1'

    implementation 'androidx.activity:activity:1.3.0-alpha08'
    implementation 'androidx.fragment:fragment:1.4.0-alpha01'

    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'com.google.android.gms:play-services-location:17.1.0'

    implementation 'com.google.firebase:firebase-core:18.0.0'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'com.google.firebase:firebase-dynamic-links:19.1.1'
    implementation 'com.google.firebase:firebase-crashlytics:17.3.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'

    implementation 'com.naver.maps:map-sdk:3.19.1'

    implementation 'com.github.bumptech.glide:glide:4.11.0'
    implementation files('libs/klog.jar')
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    implementation 'com.github.Triggertrap:SeekArc:v1.1'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.github.chthai64:SwipeRevealLayout:1.4.0'
    implementation 'com.github.nguyenhoanglam:ImagePicker:1.4.3'
    implementation 'com.github.amitshekhariitbhu:PRDownloader:1.0.2'
    implementation 'androidx.mediarouter:mediarouter:1.3.1'
    implementation ("com.github.mkaflowski:HybridMediaPlayer:1.9.4") {
        exclude group: 'com.github.zhaokaiqiang.klog', module: 'library'

    }
    implementation 'com.makeramen:roundedimageview:2.3.0'
//    implementation 'com.github.thang2162:Android-ScalableVideoView:v1.1.1'

    implementation 'com.scottyab:rootbeer-lib:0.1.1'
    implementation group: 'org.apache.commons', name: 'commons-text', version: '1.9'
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.2"
    implementation "org.glassfish.jaxb:jaxb-runtime:2.3.2"

    implementation "com.getbase:floatingactionbutton:1.10.1"

    implementation "androidx.lifecycle:lifecycle-viewmodel:2.4.0"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.4.0"
}